/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import model.patient.Patient;
import model.patient.PatientDirectory;
import model.person.Person;
import model.records.Encounter;
import model.records.EncounterHistory;
import model.records.VitalSigns;

/**
 *
 * @author bhavinbhatia
 */
public class AddVitals extends javax.swing.JPanel {

    /**
     * Creates new form AddVitals
     */
    VitalSigns newVitalSigns;
    Encounter encounter;
    EncounterHistory encounterHistory;
    Patient patient;
    PatientDirectory patientDirectory;
    
    
    
    
    public AddVitals(PatientDirectory patientDirectory) {
        initComponents();
        this.patientDirectory = patientDirectory;
      
//        
//        txtPatientId.setText("123");
//        txtpulse.setText("90");
//        txtBloodPressure.setText("100");
//        txtAlergies.setText("temp allergies");
//        txtMedication.setText("temp medication");
//        txtTemp.setText("12");
//        txtSymptoms.setText("temp sympotms");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        titlePanel = new javax.swing.JPanel();
        lblPulseRate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        lblAlergies = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        txtpulse = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtSymptoms = new javax.swing.JTextField();
        txtAlergies = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedication = new javax.swing.JTextArea();
        btnAddVitals = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        lblPulseRate.setText("Pulse Rate:");

        lblTemperature.setText("Temperature:");

        lblBloodPressure.setText("Blood Pressure:");

        lblSymptoms.setText("Symptoms:");

        lblAlergies.setText("Alergies:");

        lblMedication.setText("Medication:");

        txtMedication.setColumns(20);
        txtMedication.setRows(5);
        jScrollPane1.setViewportView(txtMedication);

        btnAddVitals.setText("Add");
        btnAddVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalsActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPulseRate)
                    .addComponent(lblTemperature)
                    .addComponent(lblBloodPressure)
                    .addComponent(lblSymptoms)
                    .addComponent(lblAlergies)
                    .addComponent(lblMedication)
                    .addComponent(jLabel1))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddVitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(txtAlergies)
                    .addComponent(txtSymptoms)
                    .addComponent(txtBloodPressure)
                    .addComponent(txtTemp)
                    .addComponent(txtpulse)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulseRate)
                    .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptoms)
                    .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergies)
                    .addComponent(txtAlergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedication)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnAddVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAlergies, txtBloodPressure, txtSymptoms, txtTemp, txtpulse});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalsActionPerformed
        // TODO add your handling code here:
                
        String patientIdStr = txtPatientId.getText();
        String pulseRateStr = txtpulse.getText();
        String tempStr = txtTemp.getText();
        String symptoms = txtSymptoms.getText();
        String allergies = txtAlergies.getText();
        String medication = txtMedication.getText();
        String bloodPressureStr = txtBloodPressure.getText();
        
        if (!validateNotNull(
                patientIdStr,
                pulseRateStr,
                tempStr,
                symptoms,
                allergies,
                medication,
                bloodPressureStr
        
        )) {
            return;
        }
        
        int existingPatientId = Integer.parseInt(patientIdStr);
        int pulseRate = Integer.parseInt(pulseRateStr);
        int temp = Integer.parseInt(tempStr);
        int bloodPressure = Integer.parseInt(bloodPressureStr);
       
        
       
        Patient patient = this.patientDirectory.getPatientById(existingPatientId);
        
        
        VitalSigns newVitalSigns = new VitalSigns(pulseRate,temp,
                bloodPressure,symptoms, allergies, medication); 
            Date date = new Date();  

        Encounter encounter =new Encounter(date, newVitalSigns);
       
        patient.getEncounterHistory().addNewEncounter(encounter);
        
        JOptionPane.showMessageDialog(this, "Vital Signs Added");
        
       
        
        txtPatientId.setText("");
        txtpulse.setText("");
        txtBloodPressure.setText("");
        txtAlergies.setText("");
        txtMedication.setText("");
        txtTemp.setText("");
        txtSymptoms.setText("");
        
        
    }//GEN-LAST:event_btnAddVitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlergies;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtAlergies;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextArea txtMedication;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtSymptoms;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtpulse;
    // End of variables declaration//GEN-END:variables

     public boolean validateNotNull(String... input){
      for (String inp : input) {
          if(inp.isEmpty()){
              JOptionPane.showMessageDialog(this, "All fields are required.");
              return false;
          }
            
      }
      return true;
     }
}
