/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.patient.Patient;
import model.patient.PatientDirectory;
import model.person.Person;

import model.records.Encounter;
import model.records.EncounterHistory;
import model.records.VitalSigns;

/**
 *
 * @author bhavinbhatia
 */
public class ViewEncounterHistory extends javax.swing.JPanel {

    /**
     * Creates new form PatientEncounter
     */
    VitalSigns newVitalSigns;
    PatientDirectory patientDirectory;
    int patientId;
    EncounterHistory encounterHistory;
    
    
    
    public ViewEncounterHistory(PatientDirectory patientDirectory) {
        initComponents();
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();
        lblTemperature = new javax.swing.JLabel();
        txtAlergies = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        lblSymptoms = new javax.swing.JLabel();
        lblAlergies = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedication = new javax.swing.JTextArea();
        txtpulse = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        lblPulseRate = new javax.swing.JLabel();
        txtSymptoms = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSelectEncounter = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        tblEncounterHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Encounter Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEncounterHistory);

        lblTemperature.setText("Temperature:");

        txtAlergies.setEditable(false);
        txtAlergies.setBackground(new java.awt.Color(204, 204, 204));

        lblBloodPressure.setText("Blood Pressure:");

        jLabel1.setText("Patient ID");

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });

        lblSymptoms.setText("Symptoms:");

        lblAlergies.setText("Alergies:");

        lblMedication.setText("Medication:");

        txtMedication.setEditable(false);
        txtMedication.setBackground(new java.awt.Color(204, 204, 204));
        txtMedication.setColumns(20);
        txtMedication.setRows(5);
        jScrollPane2.setViewportView(txtMedication);

        txtpulse.setEditable(false);
        txtpulse.setBackground(new java.awt.Color(204, 204, 204));

        txtTemp.setEditable(false);
        txtTemp.setBackground(new java.awt.Color(204, 204, 204));

        txtBloodPressure.setEditable(false);
        txtBloodPressure.setBackground(new java.awt.Color(204, 204, 204));

        lblPulseRate.setText("Pulse Rate:");

        txtSymptoms.setEditable(false);
        txtSymptoms.setBackground(new java.awt.Color(204, 204, 204));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSelectEncounter.setText("Select");
        btnSelectEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelectEncounter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPulseRate)
                                .addComponent(lblTemperature)
                                .addComponent(lblBloodPressure)
                                .addComponent(lblSymptoms)
                                .addComponent(lblAlergies)
                                .addComponent(lblMedication))
                            .addGap(115, 115, 115)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAlergies)
                                .addComponent(txtSymptoms)
                                .addComponent(txtBloodPressure)
                                .addComponent(txtTemp)
                                .addComponent(txtpulse, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtPatientId)
                            .addGap(18, 18, 18)
                            .addComponent(btnSearch))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAlergies, txtBloodPressure, txtPatientId, txtSymptoms, txtTemp, txtpulse});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectEncounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulseRate)
                    .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptoms)
                    .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergies)
                    .addComponent(txtAlergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedication)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAlergies, txtBloodPressure, txtPatientId, txtSymptoms, txtTemp, txtpulse});

    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        // Get patient Id
        int existingPatientId = Integer.parseInt(txtPatientId.getText());
        this.patientId = existingPatientId;
        Patient searchedPatient = this.patientDirectory
                .getPatientById(existingPatientId);
        EncounterHistory encounterHistory = searchedPatient.getEncounterHistory();
        this.encounterHistory = encounterHistory;
        populateEncounterHistory(encounterHistory);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSelectEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEncounterActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEncounterHistory.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog( this, "Please select the row first");
        } 
        DefaultTableModel tableModel = (DefaultTableModel) tblEncounterHistory.getModel();
        
        
       tableModel.getValueAt(selectedRowIndex, 0);
      
        Encounter encounter = this.encounterHistory.getEncounters().get(selectedRowIndex);
        this.newVitalSigns = encounter.getVitalSigns();

    
        
    txtpulse.setText(String.valueOf(newVitalSigns.getPulseRate()));
    txtTemp.setText(String.valueOf(newVitalSigns.getTemperature()));
    txtBloodPressure.setText(String.valueOf(newVitalSigns.getBloodPressure()));
    txtSymptoms.setText(newVitalSigns.getSymptoms());
    txtAlergies.setText(newVitalSigns.getAlergies());
    txtMedication.setText(newVitalSigns.getMedication());
    }//GEN-LAST:event_btnSelectEncounterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectEncounter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlergies;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JTable tblEncounterHistory;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtAlergies;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextArea txtMedication;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtSymptoms;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtpulse;
    // End of variables declaration//GEN-END:variables
public void displayVitalSigns (){


    VitalSigns newVitalSigns = new VitalSigns(50, 101, 120, "Headache", "polan", "ibrufen");
    txtpulse.setText(String.valueOf(newVitalSigns.getPulseRate()));
    txtTemp.setText(String.valueOf(newVitalSigns.getTemperature()));
    txtBloodPressure.setText(String.valueOf(newVitalSigns.getBloodPressure()));
    txtSymptoms.setText(newVitalSigns.getSymptoms());
    txtAlergies.setText(newVitalSigns.getAlergies());
    txtMedication.setText(newVitalSigns.getMedication());

}
    
    
    
    
    public void populateEncounterHistory(EncounterHistory encounterHistory){
  
     DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        
        for (Encounter encounter : encounterHistory.getEncounters()){
            Object [] row = new Object[3];
            row[0]= encounter.getDate();          
            model.addRow(row);
        }

    
    }
}
